# Generated by Django 6.1 on 2026-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
