# Generated by Django 6.1 on 2026-08-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitrecord_follow_up_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='visit',
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='admission_ward',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('discharged', 'Discharged'), ('admitted', 'Admitted'), ('referred', 'Referred')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='referral_hospital',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='visits.visitrecord')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='visits.invoice'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='visits.invoice')),
            ],
        ),
    ]
