# Generated by Django 6.1 on 2026-08-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Account Locked'), ('logout', 'Logout'), ('staff_created', 'Staff Created'), ('staff_deactivated', 'Staff Deactivated'), ('staff_reactivated', 'Staff Reactivated'), ('staff_role_changed', 'Staff Role Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed')], max_length=50)),
                ('target_email', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
