# Generated by Django 6.1 on 2026-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Account Locked'), ('logout', 'Logout'), ('staff_created', 'Staff Created'), ('staff_deactivated', 'Staff Deactivated'), ('staff_reactivated', 'Staff Reactivated'), ('staff_role_changed', 'Staff Role Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('diagnosis_access_requested', 'Diagnosis Access Requested'), ('diagnosis_access_approved', 'Diagnosis Access Approved'), ('diagnosis_access_revoked', 'Diagnosis Access Revoked')], max_length=50),
        ),
    ]
