# Generated by Django 6.1 on 2026-08-10 13:41

from django.db import migrations


def migrate_status(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    Appointment.objects.filter(status="in_progress").update(status="with_nurse")

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_is_walk_in_appointment_seen_by_doctor_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_status, migrations.RunPython.noop),
    ]
